# Project information
site_name: Twitter Growth Bot Documentation

# Navigation
nav:
  - Home: index.md
  - Methodology: methodology.md
  - Design Sprint: design_sprint.md
  - Requirements Elicitation:
    - Brainstorming: requirements/brainstorming.md
    - 5W2H: requirements/5w2h.md
    - RichPicture: requirements/rich_picture.md
    - Interviews: requirements/interviews.md
    - MindMap: requirements/mind_map.md
    - Elicited Requirements Table: requirements/requirements_table.md
  - Risk Analysis Plan: risk_plan.md
  - Prototypes: prototypes.md

theme:
  name: material
  language: 'en'
  palette:
    primary: 'light blue'
    accent: 'teal'


# Repository
repo_name: 'Twitter Growth Bot'
repo_url: 'https://github.com/fernand0aguilar/twitter-growth-bot'

